name: APK Rapida
on:
  workflow_dispatch: # Esto te permite darle al botón "Run" manualmente

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Fabricar con Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer android debug
          buildozer_version: master
