name: Fabricar mi APK
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    # Usamos la versión 22.04 que es la más estable para Kivy
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer
        # Esta acción ya tiene todo instalado y configurado correctamente
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer android debug
          buildozer_version: master

      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: Control_Anez_Final
          path: bin/*.apk
